/**
 * Tangram Invoice — Anchor IDL type definitions.
 *
 * This is the TypeScript type surface for the on-chain program.
 * The full IDL JSON will be generated by `anchor build` and placed
 * at target/idl/tangram_invoice.json — import it here for the Anchor client.
 *
 * Until the program is deployed, this file provides the shared types
 * used across hooks and components.
 */

export type InvoiceData = {
    invoiceId: string;
    exporter: string;
    buyer: string;
    amountUsdc: bigint;
    commodityCode: string;
    sustainabilityIpfsHash: string;
    carbonScore: number;
    status: number;
    nftMint: string | null;
    createdAt: bigint;
    verifiedAt: bigint | null;
    rejectionReason: string | null;
    listedAskPrice: bigint | null;
    fundedBy: string | null;
    fundedAt: bigint | null;
    completedAt: bigint | null;
    /** PDA address of this account */
    publicKey: string;
};

export type MarketplaceListing = {
    invoicePda: string;
    exporter: string;
    askPrice: bigint;
    listedAt: bigint;
    financier: string | null;
    publicKey: string;
};

export type FinancingRequest = {
    invoicePda: string;
    exporter: string;
    amount: bigint;
    requestedAt: bigint;
    fundedAt: bigint | null;
    repaidAt: bigint | null;
    publicKey: string;
};

/** Stub IDL — will be replaced by the output of `anchor build` */
export const TANGRAM_INVOICE_IDL = {
    version: '0.1.0',
    name: 'tangram_invoice',
    instructions: [
        { name: 'submitInvoice', accounts: [], args: [] },
        { name: 'verifyInvoice', accounts: [], args: [] },
        { name: 'rejectInvoice', accounts: [], args: [] },
        { name: 'createListing', accounts: [], args: [] },
        { name: 'fundInvoice', accounts: [], args: [] },
        { name: 'confirmReceipt', accounts: [], args: [] },
        { name: 'attachSustainabilityData', accounts: [], args: [] },
    ],
    accounts: [],
    errors: [],
} as const;
